#! /bin/bash

#   Add cryptsetup service files to runlevel/boot

/bin/cp /etc/init.d/dnscrypt-proxy /etc/runlevels/default || true

#   Add dmcrypt service files to runlevel/boot

rc-update add dnscrypt-proxy default

#   Update services list

rc-update -u
