#! /bin/bash

#   Add dnscrypt-proxy service files to runlevel/default

/bin/cp /etc/init.d/dnscrypt-proxy /etc/runlevels/default || true

#   Add dmcrypt service files to runlevel/boot

rc-update add dnscrypt-proxy default

#   Update services list

rc-update -u

#   Create directories for dnscrypt-proxy and change permissions

mkdir -p /var/{cache,log,run}/dnscrypt-proxy
chown _dnscrypt-proxy:nogroup /var/{cache,log,run}/dnscrypt-proxy
chmod 0775 /var/{cache,log,run}/dnscrypt-proxy
